/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_phonon_thread_PhononNativeExecutor */

#ifndef _Included_com_jme3_phonon_thread_PhononNativeExecutor
#define _Included_com_jme3_phonon_thread_PhononNativeExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_phonon_thread_PhononNativeExecutor
 * Method:    startUpdateNative
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_thread_PhononNativeExecutor_startUpdateNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jme3_phonon_thread_PhononNativeExecutor
 * Method:    stopUpdateNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_thread_PhononNativeExecutor_stopUpdateNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
