/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_phonon_PhononRenderer */

#ifndef _Included_com_jme3_phonon_PhononRenderer
#define _Included_com_jme3_phonon_PhononRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    connectSourceNative
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_phonon_PhononRenderer_connectSourceNative
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    disconnectSourceNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_disconnectSourceNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    initLineNative
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_initLineNative
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    updateNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_updateNative
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    initNative
 * Signature: (IIIIIIZZJ[JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_initNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jboolean, jboolean, jlong, jlongArray, jboolean);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_destroyNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
