/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_phonon_PhononRenderer */

#ifndef _Included_com_jme3_phonon_PhononRenderer
#define _Included_com_jme3_phonon_PhononRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    connectSourceNative
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_phonon_PhononRenderer_connectSourceNative
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    disconnectSourceNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_disconnectSourceNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    updateNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_updateNative
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    initNative
 * Signature: (J[JIJJLcom/jme3/phonon/PhononSettings;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_initNative
  (JNIEnv *, jobject, jlong, jlongArray, jint, jlong, jlong, jobject);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_destroyNative
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    startThreadNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_startThreadNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    setMeshNative
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_setMeshNative
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    unsetMeshNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_unsetMeshNative
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_phonon_PhononRenderer
 * Method:    saveMeshAsObjNative
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_jme3_phonon_PhononRenderer_saveMeshAsObjNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
