/**
* Copyright (c) 2018, Riccardo Balbo - Lorenzo Catania
* All rights reserved.
*
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
* - Redistributions of source code must retain the above copyright
*      notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*      notice, this list of conditions and the following disclaimer in the
*      documentation and/or other materials provided with the distribution.
*
* - Neither the name of the developers nor the
*      names of the contributors may be used to endorse or promote products
*      derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_phonon_memory_layout_LISTENER_LAYOUT */

#ifndef _Included_com_jme3_phonon_memory_layout_LISTENER_LAYOUT
#define _Included_com_jme3_phonon_memory_layout_LISTENER_LAYOUT
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_JNIEXPORT
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_JNIEXPORT 1L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSX_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSX_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSY_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSY_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSZ_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSZ_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRX_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRX_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRY_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRY_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRZ_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRZ_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPX_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPX_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPY_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPY_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPZ_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPZ_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELX_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELX_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELY_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELY_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELZ_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELZ_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VOLUME_fieldsize
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VOLUME_fieldsize 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSX
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSX 0L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSY
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSY 4L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSZ
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_POSZ 8L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRX
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRX 12L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRY
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRY 16L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRZ
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_DIRZ 20L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPX
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPX 24L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPY
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPY 28L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPZ
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_UPZ 32L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELX
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELX 36L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELY
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELY 40L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELZ
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VELZ 44L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VOLUME
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_VOLUME 48L
#undef com_jme3_phonon_memory_layout_LISTENER_LAYOUT_LISTENER_size
#define com_jme3_phonon_memory_layout_LISTENER_LAYOUT_LISTENER_size 52L
#ifdef __cplusplus
}
#endif
#endif
