/**
* Copyright (c) 2018, Riccardo Balbo - Lorenzo Catania
* All rights reserved.
*
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
* - Redistributions of source code must retain the above copyright
*      notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*      notice, this list of conditions and the following disclaimer in the
*      documentation and/or other materials provided with the distribution.
*
* - Neither the name of the developers nor the
*      names of the contributors may be used to endorse or promote products
*      derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT */

#ifndef _Included_com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT
#define _Included_com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_JNIEXPORT
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_JNIEXPORT 1L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_UNUSED_fieldsize
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_UNUSED_fieldsize 12L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PROCESSED_FRAME_fieldsize
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PROCESSED_FRAME_fieldsize 4L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PLAYED_FRAME_fieldsize
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PLAYED_FRAME_fieldsize 4L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_HEADER_size
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_HEADER_size 20L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_UNUSED
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_UNUSED 0L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PROCESSED_FRAME
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PROCESSED_FRAME 12L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PLAYED_FRAME
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_LAST_PLAYED_FRAME 16L
#undef com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_BODY
#define com_jme3_phonon_memory_layout_OUTPUT_LINE_LAYOUT_BODY 20L
#ifdef __cplusplus
}
#endif
#endif
