dist: trusty
sudo: required
services:
- docker
git:
  lfs_skip_smudge: true
script:
- ./make.sh TRAVIS_COMMIT,TRAVIS_TAG,TRAVIS_PULL_REQUEST,TRAVIS_BRANCH,BINTRAY_USER,BINTRAY_KEY,OS_LINUX=1,OS_WINDOWS=1,NO_CACHE=1 clean downloadResources updateJNIHeaders packageSource build buildStandaloneTests deploy -Pin_version=""
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: NA/FGqL4chP0tA/QX+8sBQK5QF3zjlPqXtARXyTZvpqIF55UDv8i6ujZ6xgTIAXyBMoydWY7yVCyqUB6pPwwWtnxyEnOeAMbYF5YDF1w/tcROR/1CIq6hgyzePJUNCY9dVLmHRvG9s1UoJ1CAkggQjKIYqkK2+O03s4YTG4l9OfOUlpg651ohM4PpXV/z2N605zjECSJdCTB09fEgk9Vk+F6Wr/m9IlRRjPcKhlDogIAO7OtpjyWwXylEelVdbwAlZEk5L7sc18xuA3Hq7z9OIfuiov7tw/T3gIgVFqturNiDCnS1GbWYm87nl5V26txx0RnYPJhpxW9MsYPl6Qfi/3rr8ciYH9Hpt5ILsqNSTFijQL1znGen01bijZ8QeEGKgWLHTg0/cMvjZytx8qJ2w21f1vMP+osDIhhm2mGUwDbfL29VFNtyG+J0zG0nIu2N8Qyg1261j6q6imkOgGnxM4zxWWN91YOwVvkJ5Jb2cq/NlF32LU6tFKcPI2y8xfpdK8MFXnPmpxfxDsCTuEo+QAqtZkSjil60zNAFU20xZALF5yhdhW/N/CXesm3ElihlzTa8nnICD7FzxTs9LMf+PyaVxTfjXzgjLBDm4W4i5dEYt9joSASsxm6Igk13hsvIo9kUxjkqrqRChjB5WVhbwVR/iPe8VsP2+WaEWh+OEE=
  file: deploy/*
  on:
    repo: jmePhonon/jmePhonon
    tags: true
env:
  global:
    - BINTRAY_USER: riccardo
    - secure: gEn4buFClUTcziW/l38eA56JpondzaWctJk3Mz0IpeL0LmkOkhQvW+gBNvpnpABsy2sknMNzTUXKGU4/dUHKF/UlynBPYw5TyxYB6y2UxtQUfKh7df3bRDgH5uSli3Q5VyAZskUBxKIVJPHuLHXnct1d+W5MWLDbeT4InfieuNWjAJt8Fy8V/h4bla5jUdfSoD/6BzjsHH/2s15sxLcke6pAb9o8SHRvCwGG+t8OOGehBRIhG9V1C2GSravpbNUscxTAiNGY2uTvxPZUwYgXWG94/7ZWjGY2KnVKgNlEWDSM/RI7BerTfcaxI8+mo+n4/KfWquswDk6+C/vYS053dGo/YLxuW3oJektCFbzv9YNTcpxfKtVfrPJUp5mrjAxi+btxly1LID7pafPKa0Nu8NP7FyAbcUigARQZmZlu4of/eIMVJQM/w0k2T4N05aUIdEACka8f+X+vFIOE8CIqnjU1vrvyP8/wwYSO2w8de9ljBuGdZInyoGpnU2EevC9VBb2LeibASvsRpuNZzvHH9iEQkJk41ghLQGuszZQiYbsh8vm2b+67RJsubpW7YxueoFTntPD2yIOsky0iQ8JAz4HH52t7cA85Ncz4mW/J6b1qIazNRdAlEzwp4+iiSEupybZnjS1+TIOJgLSSvqyV5R1M+qZ+adfxKsY6m1djLeU=
