sudo: required
services:
- docker
git:
  lfs_skip_smudge: true
script:
- ./make.sh OS_LINUX=1,OS_WINDOWS=1,NO_CACHE=1 clean downloadResources updateJNIHeaders
  packageSource build buildStandaloneTests deploy -Pin_version=""
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: NA/FGqL4chP0tA/QX+8sBQK5QF3zjlPqXtARXyTZvpqIF55UDv8i6ujZ6xgTIAXyBMoydWY7yVCyqUB6pPwwWtnxyEnOeAMbYF5YDF1w/tcROR/1CIq6hgyzePJUNCY9dVLmHRvG9s1UoJ1CAkggQjKIYqkK2+O03s4YTG4l9OfOUlpg651ohM4PpXV/z2N605zjECSJdCTB09fEgk9Vk+F6Wr/m9IlRRjPcKhlDogIAO7OtpjyWwXylEelVdbwAlZEk5L7sc18xuA3Hq7z9OIfuiov7tw/T3gIgVFqturNiDCnS1GbWYm87nl5V26txx0RnYPJhpxW9MsYPl6Qfi/3rr8ciYH9Hpt5ILsqNSTFijQL1znGen01bijZ8QeEGKgWLHTg0/cMvjZytx8qJ2w21f1vMP+osDIhhm2mGUwDbfL29VFNtyG+J0zG0nIu2N8Qyg1261j6q6imkOgGnxM4zxWWN91YOwVvkJ5Jb2cq/NlF32LU6tFKcPI2y8xfpdK8MFXnPmpxfxDsCTuEo+QAqtZkSjil60zNAFU20xZALF5yhdhW/N/CXesm3ElihlzTa8nnICD7FzxTs9LMf+PyaVxTfjXzgjLBDm4W4i5dEYt9joSASsxm6Igk13hsvIo9kUxjkqrqRChjB5WVhbwVR/iPe8VsP2+WaEWh+OEE=
  file: deploy/*
  on:
    repo: jmePhonon/jmePhonon
    tags: true
env:
  global:
  - secure: gdC6+AIdLp+3rVX+mK+2qRlvbjk8xHxhRjPekPAsTrsBFomZq7JLVpj+JQovTHsZ/mEHdO5cQUXMvoRet59zSMPfg2RTkmyU/xPQMlyViOZQBS82AcRa2/5Qrmkj2vHUYRmE1hz3KX2hBClQ6gATviPtfpBP/bFFdY1KtLU57vqcXC7cDTyHcXk4Vhcxfd8E4XF1li0hQ8aSaj9Dx/NUrZ4LLcX+0ZaOtwdNA7gBiWS3YnRPWBuCC2gVxhahgsPQY5Kc/cbTAcPHV/G2+tRiLT/UUNAOdkMGGMDl7HVMRlMCxFumumqhaFatM7+hdjCOk495Zc+vb2O+jGhN0W6IyPVpbUjRMvtAiqW5ORJrC46ofxnw/vVjQnDKgj3ENEm8yEgn0sLHWx7Gjl5mU9QBpxXzrRdp9P3eAZeWNifycM8I4ZxZzH6YVwivLNvOZCrmOPx/6uM1keTsuKYbJL4lHX0PWKYUKcjyc7iY6vCGDlKSxLCyYgwo2XZhFwN/uu32MzSVyajrx7ZPsHAwtgmGQHFKI4yAT4a5nXDnP1x8nqJKfoQjDxAF4eY37RgaPfApSh9Mtk+76k5yCzNhwQs6C94ITAi1aE8v5lQ0hCygDkyM62dCleUFIywTqhL+jBkAUswIEaDrfZI1Qb7KNelfLckH2X7c7tnFSRx7Mujl0sM=
  - secure: fnBbWtLXjJi6tCMHarso2gT+RtSESGnkQcHrTl/Q+NmeTTfCMThiH4ppGaQaJx/YjcxjbKo7y8mZot+RGdG7iIB4ToQhAGa9gVBCZNvIdaE7RS1rQt11Kpu/sgnLMWgSNco1XPSMpqBIba1g7oHHhsGX9/BhGtp1cD1BKM5HuNW9ZCLGVWQfd1KkxHPv3H2POnuy0tZEM3CZoK3MArFeCMn1/9MRc5b3C31C+GYUmgaVmK57LUmNGlJxPGid2ZiQIgIOamnq/Y0SJlOclq8pM5JOZ1J+2ktv+lLQyCPpY0VupegrT68mUt/wc6KOsc8rJcpt5fYDyUBj4HrLTzbpjYMgyXpr8vJRbSAzyu+nRYBNInQt/DDg8LPKL5BoAJAKSjXBZTcxHIb0ZOwatGwXpD2nSjGZ4Gt36/6tcISfIFWZL2H0CTDwG+neClhKERJ7KYXlk3AQCVmSd/WNOUrV4Gd8kvQxExpNt18K+sRw3JLMV2GuUqLyjqvQqX0PD57L18zbnHHh+Oy8eoIHrGuF67C6mE7PbS5HRJuNrlqhGJujp5lBevBZpZSv1gbfktixXza1Z9CIMGxE2g2dTm/CSEoNxSpUVWcjv1/VbX2DmSJhkLQ5gP2+8dA7CS+7cW13wmLLVpFE9n+SjJv9XeHYaz0j4WnvqcRUsBY51/75RUQ=
