name: Build jmePhonon
on:
  push:
  pull_request:
  release:
    types: [published]
  
jobs:
  
  # Build the natives
  BuildNatives:
    strategy:
      fail-fast: true
      matrix:
        osName: [linux,windows,mac] 
        jdk: [8.x.x]
        include:
          - osName: linux
            os: ubuntu-latest
          - osName: windows
            os: ubuntu-latest
          - osName: mac
            os: macos-11.0
              
    name: Build for ${{ matrix.osName }}
    runs-on: ${{ matrix.os }}    
    steps:    
    
      - name: Clone the repo
        uses: actions/checkout@v2     
        with:
          fetch-depth: 1
           
      - name: Prepare java environment
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
          architecture: x64
     
      - name: Build on Linux
        if:  matrix.osName  == 'linux'
        run: |
          ./make.sh TRASH=notrash,OS_LINUX=1,NO_CACHE=1 clean downloadResources  updateJNIHeaders build buildStandaloneTests install  -Dmaven.repo.local="deploy" -Pin_version="-SNAPSHOT"
            
          
      - name: Build on Windows
        if:  matrix.osName  == 'windows'
        run: |
          ./make.sh TRASH=notrash,OS_WINDOWS=1,NO_CACHE=1  clean downloadResources  updateJNIHeaders build buildStandaloneTests install  -Dmaven.repo.local="deploy" -Pin_version="-SNAPSHOT"
            
          
      - name: Build on Mac
        if:  matrix.osName  == 'mac'
        shell: bash
        run: |
          brew install coreutils findutils
          export TRASH=notrash 
          export OS_OSX=1 
          export NO_CACHE=1 
          export GRADLE_USER_HOME=$PWD/build.cache 
          ./build.sh downloadResources
          ./build.sh updateJNIHeaders 
          ./build.sh buildNatives 
          gradle build buildStandaloneTests install  -Dmaven.repo.local="deploy" -Pin_version="-SNAPSHOT"
            
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.osName }}-maven
          path: deploy/
            
